title: Anna Wilde
description: >- 
  Anna Wilde - Heilpraktikerin für Psychotherapie, Systemische Therapeutin für Einzel-, Paar- & Familientherapie (SG) 
  / Licensed non-medical practitioner for Psychotherapy Systemic Individual, Couples & Family Therapy (SG)
url: "https://annawilde.de" 

future: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-dotenv
