title: Anna Wilde
description: >- # this means to ignore newlines until "baseurl:"
  Neukölln's non-profit art cooperative.
url: "https://annawilde.de" # the base hostname & protocol for your site, e.g. http://example.com

future: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-dotenv
